name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  pull_request_validation:
    name: Pull Request Validation
    environment: pull-requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run ng build
      - run: npm run ng lint
